services:
  moneytree:
    build: .
    volumes:
      - ./data:/app/data
      - ./backend/uploads:/app/backend/uploads
    env_file:
      - .env
    networks:
      - npm_network

networks:
  npm_network:
    external: true
