"""initial schema

Revision ID: fc15ca4be708
Revises: 
Create Date: 2026-02-17 23:51:30.311722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc15ca4be708'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_bank_category', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('rekening', sa.String(length=34), nullable=False),
    sa.Column('tegenrekening', sa.String(length=34), nullable=True),
    sa.Column('naam', sa.String(length=255), nullable=True),
    sa.Column('adres', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('woonplaats', sa.String(length=100), nullable=True),
    sa.Column('valuta_saldo', sa.String(length=3), nullable=False),
    sa.Column('saldo_voor_boeking', sa.Float(), nullable=False),
    sa.Column('valuta', sa.String(length=3), nullable=False),
    sa.Column('bedrag', sa.Float(), nullable=False),
    sa.Column('verwerkingsdatum', sa.Date(), nullable=False),
    sa.Column('valutadatum', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('volgnummer', sa.String(length=20), nullable=False),
    sa.Column('betalingskenmerk', sa.String(length=255), nullable=True),
    sa.Column('omschrijving', sa.Text(), nullable=False),
    sa.Column('afschriftnummer', sa.String(length=20), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('import_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_hash')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_items')
    op.drop_table('receipts')
    op.drop_table('transactions')
    op.drop_table('categories')
    # ### end Alembic commands ###
